version: '3.3'

services:
  development:
    build: ./
    hostname: "dev"
    working_dir: /home/node/src
    container_name: nb-slug
    environment:
      - NODE_ENV=development
    volumes:
      - $PWD:/home/node/src
      - $PWD/.bashrc:/home/node/.bashrc
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
